"""Preserve source PNGs; bake ordered home decorations and pack lossless runtime atlases."""
from pathlib import Path
from PIL import Image
import json, hashlib, io

OUT = Path('assets/runtime-ui')
OUT.mkdir(parents=True, exist_ok=True)
def read(name):
    return json.loads(Path('src', name).read_text(encoding='utf-8').split('export default ',1)[1].rstrip().removesuffix(';'))
def write_module(name, data):
    Path('src',name).write_text('// Generated by scripts/build-runtime-art.py; source layers are preserved.\nexport default '+json.dumps(data,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
def save(image, prefix):
    stream=io.BytesIO();image.save(stream,format='WEBP',lossless=True,method=6,exact=True)
    data=stream.getvalue();name=prefix+'-'+hashlib.sha256(data).hexdigest()[:12]+'.webp'
    (OUT/name).write_bytes(data)
    return 'assets/runtime-ui/'+name

home=read('home-art-manifest.js')
original_home=json.loads(json.dumps(home))
assets={}; layers=[]; batch=[]; static=[]
def flush():
    if not batch:return
    canvas=Image.new('RGBA',(941,1672))
    for id in batch:
        spec=original_home['assets'][id];im=Image.open(Path(original_home['directory'])/spec['file']).convert('RGBA')
        x,y,w,h=spec['bounds']
        assert im.size==(w,h)
        if spec['opacity']!=1:im.putalpha(im.getchannel('A').point(lambda a:round(a*spec['opacity'])))
        canvas.alpha_composite(im,(x,y))
    box=canvas.getbbox();im=canvas.crop(box);id='static_'+str(len(static))
    path=save(im,'home-'+id)
    assets[id]={'file':Path(path).name,'bounds':[box[0],box[1],im.width,im.height],'opacity':1}
    layers.append(id);static.append({'id':id,'sources':list(batch),'path':path});batch.clear()
for id in home['layers']:
    if id.startswith(('ui_sleep_','ui_settings_')):
        flush(); assets[id]=dict(home['assets'][id]);assets[id]['file']='../home-v2/'+assets[id]['file'];layers.append(id)
    else:batch.append(id)
flush()
home['directory']='assets/runtime-ui';home['assets']=assets;home['layers']=layers;home['version']='home-runtime-atlas-v1'
write_module('home-runtime-manifest.js',home)

aliases=read('image-aliases.js')
groups={k:[] for k in ['home-controls','currency','play','settings','complete']}
for id in original_home['layers']:
    if id.startswith(('ui_sleep_','ui_settings_')):groups['home-controls'].append(original_home['directory']+'/'+original_home['assets'][id]['file'])
core=read('art-manifest.js')
for spec in core['assets'].values():groups['currency' if spec.get('group')=='06_RESOURCES' else 'play'].append(core['directory']+'/'+spec['file'])
for name,group in [('pause-art-manifest.js','settings'),('complete-art-manifest.js','complete')]:
    m=read(name);groups[group]+=[m['directory']+'/'+s['file'] for s in m['assets'].values()]
groups['settings']+=['assets/tool-dialog-v1/ui_tool_close_v1.png','assets/tool-dialog-v1/ui_tool_purchase_disabled_v1.png']
mapping={};pages=[]
for group,paths in groups.items():
    paths=list(dict.fromkeys(aliases.get(p,p) for p in paths))
    entries=[(p,Image.open(p).convert('RGBA')) for p in paths]
    entries.sort(key=lambda t:(-t[1].height,-t[1].width,t[0]))
    sheets=[]
    for path,im in entries:
        assert im.width+4<=2048 and im.height+4<=2048,(path,im.size)
        placed=False
        for sheet in sheets:
            for row in sheet['rows']:
                if im.height+4<=row['h'] and row['x']+im.width+4<=2048:
                    x,y=row['x']+2,row['y']+2;row['x']+=im.width+4;placed=True;break
            if not placed and sheet['height']+im.height+4<=2048:
                row={'x':im.width+4,'y':sheet['height'],'h':im.height+4};sheet['rows'].append(row)
                x,y=2,row['y']+2;sheet['height']+=row['h'];placed=True
            if placed:break
        if not placed:
            sheet={'rows':[{'x':im.width+4,'y':0,'h':im.height+4}],'height':im.height+4,'items':[]};sheets.append(sheet);x,y=2,2
        sheet['items'].append((path,im,x,y))
    for index,sheet in enumerate(sheets):
        width=max(x+im.width+2 for _,im,x,y in sheet['items']);height=sheet['height']
        atlas=Image.new('RGBA',(width,height))
        for path,im,x,y in sheet['items']:atlas.paste(im,(x,y))
        atlas_path=save(atlas,group+'-'+str(index));pages.append(atlas_path)
        decoded=Image.open(atlas_path).convert('RGBA')
        for path,im,x,y in sheet['items']:
            assert decoded.crop((x,y,x+im.width,y+im.height)).tobytes()==im.tobytes(),path
            mapping[path]={'file':atlas_path,'rect':[x,y,im.width,im.height]}
write_module('runtime-atlas-manifest.js',mapping)
# Keep an explicit report of source paths and outputs; no text is rasterized here.
report={'staticHomeLayers':static,'atlasPages':pages,'sourceSprites':len(mapping),'runtimeImages':len(static)+len(pages),'bytes':sum(Path(p).stat().st_size for p in pages+[s['path'] for s in static])}
(OUT/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({k:v for k,v in report.items() if k not in ['staticHomeLayers','atlasPages']}))

