"""Generate shared runtime image paths for pixel-identical PNG resources."""
from pathlib import Path
from PIL import Image
import hashlib
import json

def main():
    groups = {}
    roots = ['home-v2', 'toyhouse-ui-v3', 'pause-dialog-v2', 'tool-dialog-v1', 'level-complete-v1']
    for root in roots:
        for path in sorted((Path('assets') / root).glob('*.png')):
            image = Image.open(path).convert('RGBA')
            digest = hashlib.sha256(str(image.size).encode() + image.tobytes()).hexdigest()
            groups.setdefault(digest, []).append(path.as_posix())
    aliases = {path: paths[0] for paths in groups.values() for path in paths[1:]}
    Path('src/image-aliases.js').write_text('// Generated by scripts/deduplicate-ui-images.py; matching RGBA pixels and dimensions.\nexport default ' + json.dumps(aliases, indent=2) + ';\n', encoding='utf-8')
    print(f'{len(aliases)} duplicate resource paths share existing image requests')

if __name__ == '__main__':
    main()
