"""Reuse the approved login PSD bar in gameplay; exclude surrounding decorations."""
from pathlib import Path
import hashlib
import json
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'outputs/login-screen-layered-v1'
DEST = ROOT / 'assets/combo-login-v1'
DEST.mkdir(parents=True, exist_ok=True)
manifest_path = ROOT / 'src/art-manifest.js'
manifest = json.loads(manifest_path.read_text(encoding='utf-8').split('export default ', 1)[1].strip().removesuffix(';'))
source = json.loads((SOURCE / 'psd-manifest.json').read_text(encoding='utf-8'))
layers = {s['name']: s for g in source['groups'] for s in g['layers']}
mapping = {'combo_base': 'ui_loading_frame', 'combo_track': 'ui_loading_track',
           'combo_fill': 'ui_loading_fill', 'combo_star': 'ui_loading_cursor'}
mapping.update({f'combo_inner_star_{i:02}': f'ui_loading_star_{i:02}' for i in range(1, 8)})
# Keep the existing HUD width/center; allow space above for the cursor's ears.
scale = 466 / 490
frame_x, frame_y = 238, 212
track_x, track_y = frame_x + 13 * scale, frame_y + 14 * scale
track_w, track_h = 465 * scale, 38 * scale
for name, source_id in mapping.items():
    spec = layers[source_id]
    p = SOURCE / spec['file']
    image = Image.open(p).convert('RGBA')
    image = image.crop((2, 2, image.width - 2, image.height - 2))
    image.save(DEST / (name + '.png'))
    x, y, w, h = spec['source_bounds']
    x, y, w, h = frame_x + (x - 226) * scale, frame_y + (y - 1387) * scale, w * scale, h * scale
    if name == 'combo_fill':
        x, y, w, h = track_x, track_y, track_w, track_h
    if name.startswith('combo_inner_star_'):
        index = int(name.rsplit('_', 1)[1])
        x = track_x + track_w * index / 8 - w / 2
        y = track_y + (track_h - h) / 2
    manifest['assets'][name] = dict(file=name + '.png', directory='assets/combo-login-v1',
        size=list(image.size), bounds=[x, y, x + w, y + h], opacity=1, role='ui', group='03_COMBO',
        source=str(p.relative_to(ROOT)).replace('\\', '/'),
        sourceSha256=hashlib.sha256(p.read_bytes()).hexdigest(),
        sha256=hashlib.sha256((DEST / (name + '.png')).read_bytes()).hexdigest())
for name in ['combo_sparkle_1', 'combo_sparkle_2']:
    manifest['assets'].pop(name, None)
manifest['comboArt'] = dict(version='login-screen-bar-v1', sourcePsd='outputs/login-screen-layered-v1/login-screen-layered-v1.psd',
    assets=mapping, excluded='外围星星、光点、粒子轨迹、粉色发光装饰、云朵、月牙、兔头和Loading文字不属于Combo条。')
manifest_path.write_text('// Generated by scripts/export-core-ui-v4.py and scripts/export-combo-login-art.py.\nexport default ' + json.dumps(manifest, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
(DEST / 'report.json').write_text(json.dumps(manifest['comboArt'], ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(f'Exported {len(mapping)} independent Combo bar sprites; no surrounding stars or light particles.')
