"""Export the actual v5 PSD layers; never use the flattened preview as game art.

Usage: python scripts/export-psd-assets.py
Requires Pillow and psd-tools (the project's existing PSD tooling is reused).
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "outputs/layered_psd_v1/python_deps"))
from psd_tools import PSDImage
from PIL import Image

SOURCE = ROOT / "outputs/layered_psd_v5/toyhouse-gameplay-layered-v5.psd"
OUTPUT = ROOT / "assets/toyhouse-v5"
SPRITES = {
    "toy_rabbit_white_a": "rabbit",
    "toy_duck_yellow_a": "duck",
    "toy_whale_blue_a": "whale",
    "toy_bear_brown_a": "bear",
}


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    psd = PSDImage.open(SOURCE)
    assets, excluded = {}, []
    for layer in psd.descendants():
        if layer.is_group():
            continue
        name = layer.name
        if layer.kind == "type" or not layer.is_visible() or "rabbit_lie" in name:
            excluded.append(name)
            continue
        if name.startswith("toy_") and name not in SPRITES:
            excluded.append(name)
            continue
        # Final v5 layers use PSD user masks. topil() returns the unmasked black
        # backing; composite() applies that mask and preserves transparent edges.
        pixels = layer.composite().convert("RGBA")
        # Trim sprite padding only; retain the original bounds for UI assembly.
        original_bounds = list(layer.bbox)
        if name in SPRITES:
            pixels = pixels.crop(pixels.getbbox())
        filename = f"{name}.png"
        pixels.save(OUTPUT / filename, optimize=True)
        with Image.open(OUTPUT / filename) as check:
            assert check.mode == "RGBA" and check.size == pixels.size
            assert check.tobytes() == pixels.tobytes()
            if name != "art_bedroom_bg_01":
                assert check.getchannel("A").getextrema()[0] == 0, name
        assets[name] = {
            "file": filename,
            "bounds": original_bounds,
            "size": list(pixels.size),
            "opacity": layer.opacity / 255,
            "role": SPRITES.get(name, "ui"),
            "sha256": hashlib.sha256((OUTPUT / filename).read_bytes()).hexdigest(),
        }
    manifest = {
        "source": SOURCE.relative_to(ROOT).as_posix(),
        "sourceSha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        "canvas": list(psd.size),
        "policy": "Actual visible v5 PSD layers. Sitting white rabbit source rotates at runtime so ears indicate travel direction; no lying-pose assets or flattened reference. Text is rendered dynamically in SimHei.",
        "assets": assets,
        "excluded": excluded,
    }
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (ROOT / "src/art-manifest.js").write_text(
        "// Generated by scripts/export-psd-assets.py from the actual v5 PSD.\nexport default "
        + json.dumps({"canvas": manifest["canvas"], "assets": assets}, ensure_ascii=False, indent=2)
        + ";\n", encoding="utf-8")
    print(f"Exported and reopened {len(assets)} RGBA assets; excluded {len(excluded)} layers.")


if __name__ == "__main__":
    main()
