"""Export UI from the approved V3 PSD and art from 原画资源, without resampling."""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "outputs/20260915_ui_psd_v1/python-deps"))
from psd_tools import PSDImage
from PIL import Image

SOURCE = ROOT / "outputs/20260916_ui_proportions_v3/toyhouse-core-ui-layered-v3.psd"
OUTPUT = ROOT / "assets/toyhouse-ui-v3"
GROUPS = {"04_TITLE", "05_NAVIGATION", "06_RESOURCES", "07_COMBO", "08_TOOL_BUTTONS"}
ORIGINALS = {"art_bedroom_bg_01": "背景2",
             "toy_rabbit_white_a": "兔子3-短版", "toy_whale_blue_a": "鲸鱼4", "toy_duck_yellow_a": "鸭子3"}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    psd = PSDImage.open(SOURCE)
    assets = {}

    def save(name, pixels, **metadata):
        target = OUTPUT / f"{name}.png"
        pixels.save(target, optimize=True)
        with Image.open(target) as check:
            assert check.tobytes() == pixels.tobytes()
        assets[name] = dict(file=target.name, size=list(pixels.size), sha256=sha(target), **metadata)

    for group in psd:
        if group.name not in GROUPS:
            continue
        for layer in group.descendants():
            if layer.is_group() or layer.kind == "type" or not layer.is_visible():
                continue
            save(layer.name, layer.composite().convert("RGBA"), bounds=list(layer.bbox),
                 opacity=layer.opacity / 255, role="ui", group=group.name, sourceLayer=layer.name)
    for name, stem in ORIGINALS.items():
        source = ROOT / "原画资源" / f"{stem}.png"
        pixels = Image.open(source).convert("RGBA")
        original_size = list(pixels.size)
        # Supplied cutouts contain stray alpha=1 pixels far outside the artwork,
        # especially above/below the whale. Exclude that invisible dust from fitting.
        alpha = pixels.getchannel("A")
        crop = alpha.getbbox()
        if name.startswith("toy_"):
            l, t, r, b = alpha.point(lambda value: 255 if value > 1 else 0).getbbox()
            crop = (max(0, l - 4), max(0, t - 4), min(pixels.width, r + 4), min(pixels.height, b + 4))
        pixels = pixels.crop(crop)
        save(name, pixels, bounds=[0, 0, *pixels.size], opacity=1, role="original-art",
             source=source.relative_to(ROOT).as_posix(), sourceSha256=sha(source),
             originalSize=original_size, alphaCrop=list(crop))
    manifest = dict(version="toyhouse-ui-v3", directory="assets/toyhouse-ui-v3",
                    source=SOURCE.relative_to(ROOT).as_posix(), sourceSha256=sha(SOURCE),
                    canvas=list(psd.size), assets=assets,
                    policy="Actual V3 PSD UI layers; original artwork overrides PSD playmat/toys. Dynamic game text, no baked sample balances or hidden reference. Uniform art scaling.")
    encoded = json.dumps(manifest, ensure_ascii=False, indent=2)
    (OUTPUT / "manifest.json").write_text(encoded + "\n", encoding="utf-8")
    (ROOT / "src/art-manifest.js").write_text("// Generated by scripts/export-v3-art.py.\nexport default " + encoded + ";\n", encoding="utf-8")
    print(f"Verified {len(assets)} exports: {len(assets)-len(ORIGINALS)} V3 UI layers + {len(ORIGINALS)} original artworks.")


if __name__ == "__main__":
    main()
