"""Export the validated loading PSD assets into two lossless runtime images."""
from pathlib import Path
import hashlib, io, json, base64
from PIL import Image

ROOT=Path(__file__).resolve().parent.parent
source=ROOT/'outputs/loading-layered-v1'
out=ROOT/'assets/loading-v1'
out.mkdir(parents=True,exist_ok=True)
m=json.loads((source/'psd-manifest.json').read_text('utf8'))
checks=json.loads((source/'checksums.json').read_text('utf8'))
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
assert digest(source/m['output'])==checks[m['output']]
assert json.loads((source/'qa/delivery-validation.json').read_text('utf8'))['valid']
def save(im,prefix):
    b=io.BytesIO();im.save(b,format='WEBP',lossless=True,method=6,exact=True)
    data=b.getvalue();name=prefix+'-'+hashlib.sha256(data).hexdigest()[:12]+'.webp'
    (out/name).write_bytes(data);return name
assets={};images={}
for group in m['groups']:
    for s in group['layers']:
        p=source/s['file'];assert digest(p)==checks[s['file']]
        im=Image.open(p).convert('RGBA');images[s['name']]=im
        assets[s['name']]={'bounds':[s['left'],s['top'],*im.size],'source':s['file'],'sha256':digest(p)}
# Reuse the existing approved login logo, independently placed above the room.
logo_source=ROOT/'outputs/login-screen-layered-v1/layers/art_logo_goodnight_toyhouse.png'
logo=Image.open(logo_source).convert('RGBA')
logo_id='art_logo_goodnight_toyhouse'
images[logo_id]=logo
assets[logo_id]={'bounds':[(941-logo.width)//2,66,*logo.size],
    'source':str(logo_source.relative_to(ROOT)).replace('\\','/'),'sha256':digest(logo_source)}
background=save(images['art_loading_background'],'background')
x=y=rowh=0;rects={}
for id,im in sorted(images.items(),key=lambda kv:-kv[1].height):
    if id=='art_loading_background':continue
    if x+im.width+4>1024:x=0;y+=rowh;rowh=0
    rects[id]=[x+2,y+2,*im.size];x+=im.width+4;rowh=max(rowh,im.height+4)
atlas=Image.new('RGBA',(1024,y+rowh))
for id,r in rects.items():atlas.paste(images[id],r[:2]);assets[id]['rect']=r
atlas_name=save(atlas,'ui')
decoded=Image.open(out/atlas_name).convert('RGBA')
for id,(x,y,w,h) in rects.items():assert decoded.crop((x,y,x+w,y+h)).tobytes()==images[id].tobytes()
def inline_preview(im,resize=None):
    if resize:im=im.resize(resize,Image.Resampling.LANCZOS)
    b=io.BytesIO();im.save(b,format='WEBP',quality=72,method=6,alpha_quality=100)
    return 'data:image/webp;base64,'+base64.b64encode(b.getvalue()).decode('ascii')
data={'version':'loading-layered-v1','canvas':[m['canvas']['width'],m['canvas']['height']],'directory':'assets/loading-v1','background':background,'atlas':atlas_name,'fallbackBackground':inline_preview(images['art_loading_background'],(540,960)),'fallbackAtlas':inline_preview(atlas),'layers':list(assets),'assets':assets,'text':m['text_layers'][0],'sourcePsd':str((source/m['output']).relative_to(ROOT)).replace('\\','/')}
(ROOT/'src/loading-art-manifest.js').write_text('// Generated by scripts/export-loading-art.py.\nexport default '+json.dumps(data,ensure_ascii=False,indent=2)+';\n',encoding='utf8')
report={'sourcePsd':data['sourcePsd'],'psdSha256':checks[m['output']],'runtimeImages':[background,atlas_name],'bytes':sum((out/f).stat().st_size for f in [background,atlas_name]),'independentSprites':len(assets),'losslessAtlasVerified':True}
(out/'report.json').write_text(json.dumps(report,indent=2),encoding='utf8')
print(json.dumps(report))
