"""Export approved layered UI artwork, excluding the board and sample counter."""
import hashlib
import json
from pathlib import Path
import shutil
from PIL import Image
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'outputs/core-gameplay-2-arttype-v4'
DEST = ROOT / 'assets/core-ui-v4'
DEST.mkdir(parents=True, exist_ok=True)
manifest_path = ROOT / 'src/art-manifest.js'
old = json.loads(manifest_path.read_text(encoding='utf-8').split('export default ', 1)[1].strip().removesuffix(';'))
assets = {key: dict(spec, directory=spec.get('directory', old['directory']))
          for key, spec in old['assets'].items() if spec.get('role') == 'original-art'}
source = json.loads((SOURCE / 'psd-manifest.json').read_text(encoding='utf-8'))

def export(name, path, bounds, group):
    target = DEST / (name + '.png')
    shutil.copyfile(path, target)
    assets[name] = dict(file=target.name, size=list(Image.open(target).size),
                        sha256=hashlib.sha256(target.read_bytes()).hexdigest(),
                        bounds=bounds, opacity=1, role='ui', group=group)

for group in source['groups']:
    for layer in group['layers']:
        name = layer['name']
        if name.startswith('board_') or name == 'art_combo_value_5':
            continue
        x, y, w, h = layer['logical_bounds']
        category = '06_RESOURCES' if name.startswith(('gem_', 'coin_')) else '04_TITLE' if name.startswith('level_') else group['name']
        export(name, SOURCE / layer['file'], [x, y, x+w, y+h], category)
for digit in range(10):
    export(f'digit_{digit}', SOURCE / f'glyphs/digit_{digit}.png', [0, 0, 96, 128], 'COMBO_GLYPHS')

# Color-only frame revision: retain the original geometry, alpha and placement.
def save_revision(name, image, bounds=None):
    target = DEST / (name + '.png')
    image.save(target)
    assets[name]['size'] = list(image.size)
    assets[name]['sha256'] = hashlib.sha256(target.read_bytes()).hexdigest()
    if bounds is not None:
        assets[name]['bounds'] = bounds

track = Image.open(SOURCE / 'layers/combo_track.png').convert('RGBA')
pixels = np.array(track)
original_rgb = pixels[:, :, :3].copy()
tone = pixels[:, :, :3].mean(axis=2) / 255
for channel, (low, high) in enumerate([(243, 255), (229, 252), (208, 242)]):
    pixels[:, :, channel] = low + (high-low) * tone
# Only tint the inset capsule. Preserve the original pink contour, highlights
# and alpha exactly outside this mask, including both rounded end caps.
yy, xx = np.mgrid[:track.height, :track.width]
distance = np.hypot(xx - np.clip(xx, 23, track.width-24), yy-(track.height-1)/2)
mask = np.clip(14-distance, 0, 1)[:, :, None]
pixels[:, :, :3] = np.rint(original_rgb*(1-mask)+pixels[:, :, :3]*mask).astype('uint8')
save_revision('combo_track', Image.fromarray(pixels))
word = Image.open(SOURCE / 'glyphs/art_combo.png').convert('RGBA')
word = word.crop(word.getchannel('A').getbbox())
save_revision('art_combo_label', word, [367,160,488,192])
for name, center in [('remove',192), ('shuffle',468), ('flip',747)]:
    path = ROOT / f'art/core-ui-v5/{name}-label.png'
    image = Image.open(path).convert('RGBA')
    width = round(image.width * 44 / image.height)
    export(f'{name}_label', path, [center-width/2,1592,center+width/2,1636], 'TOOL_LETTERING')
    # Store at 3x display size for high-density screens without atlas bloat.
    save_revision(f'{name}_label', image.resize((width*3,132),Image.Resampling.LANCZOS))

manifest = dict(version='core-ui-v4', directory='assets/core-ui-v4', canvas=[941, 1672],
                revision='preserved-pink-rim-pastel-lettering-v7',
                text={t['name']: t for t in source['text_layers']},
                source='outputs/core-gameplay-2-arttype-v4/psd-manifest.json', assets=assets)
manifest_path.write_text('// Generated by scripts/export-core-ui-v4.py.\nexport default '+json.dumps(manifest, ensure_ascii=False, indent=2)+';\n', encoding='utf-8')
print(f'Exported {len(assets)} assets; no board or fixed combo sample included.')
