"""Export PSD-verified layers and approved tool-specific artwork without editing sources."""
from pathlib import Path
import json, shutil, hashlib
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
base = ROOT / 'outputs/eliminate-popup2-layered-v1'
other = ROOT / 'outputs/flip-popup2-layered-v1'
dest = ROOT / 'assets/tool-popup2-v1'
dest.mkdir(parents=True, exist_ok=True)
read = lambda p: json.loads(p.read_text('utf-8'))
m = read(base / 'psd-manifest.json')
audit = read(base / 'qa/layer-placement-and-pixel-audit.json')
assert audit['all_positions_match'] and audit['all_png_pixels_match']
assets, common, remove, shuffle, purchase, close = {}, [], [], [], [], []

def add(name, source, bounds, resize=False):
    target = dest / (name + '.png')
    if resize:
        im = Image.open(source).convert('RGBA')
        im = im.crop(im.getbbox())
        im.thumbnail((bounds[2], bounds[3]), Image.Resampling.LANCZOS)
        bounds = [bounds[0]+(bounds[2]-im.width)/2, bounds[1]+(bounds[3]-im.height)/2, im.width, im.height]
        im.save(target)
    else:
        shutil.copyfile(source, target)
    assets[name] = dict(file=target.name, bounds=bounds, source=source.relative_to(ROOT).as_posix(), sha256=hashlib.sha256(target.read_bytes()).hexdigest())

for group in m['groups']:
    for spec in group['layers']:
        name = spec['name']
        add(name, base / spec['file'], spec['logical_bounds'])
        if name.startswith('close_'): close.append(name)
        elif group['name']=='05_PURCHASE': purchase.append(name)
        elif group['name']=='03_ILLUSTRATION' and not name.startswith('illustration_'): remove.append(name)
        else: common.append(name)
for group in read(other/'psd-manifest.json')['groups']:
    if group['name']=='03_SHUFFLE_ICON':
        for spec in group['layers']:
            name='shuffle_'+spec['name']
            add(name, other/spec['file'], spec['logical_bounds'])
            shuffle.append(name)
add('use_base', other/'layers/use_button_base.png', [220,1122,499,143], True)
title_bounds = [395,414,163,81]
add('title_flip', other/'layers/arttext_flip.png', title_bounds, True)
add('title_shuffle', ROOT/'output/imagegen/shuffle-arttext-v1/arttext_shuffle.png', title_bounds, True)
add('icon_flip', ROOT/'outputs/flip-tool-icon-v1/ui_tool_flip.png', [318,604,310,310], True)
manifest = dict(version='tool-popup2-v1', directory='assets/tool-popup2-v1', canvas=m['canvas'], source=(base/m['output']).relative_to(ROOT).as_posix(), assets=assets, common=common, close=close, purchase=purchase, icons=dict(remove=remove, shuffle=shuffle, flip=['icon_flip']), titles=dict(remove=None,shuffle='title_shuffle',flip='title_flip'), textLayers=m['text_layers'])
(dest/'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
(ROOT/'src/tool-art-manifest.js').write_text('// Generated by scripts/export-tool-dialog-art.py.\nexport default '+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Exported {len(assets)} tool dialog resources')
