// Generated by scripts/deduplicate-ui-images.py; matching RGBA pixels and dimensions.
export default {
  "assets/toyhouse-ui-v3/ui_bottom_button_disc_01_instance_02.png": "assets/toyhouse-ui-v3/ui_bottom_button_disc_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_bottom_button_disc_01_instance_03.png": "assets/toyhouse-ui-v3/ui_bottom_button_disc_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_bottom_label_plate_01_instance_02.png": "assets/toyhouse-ui-v3/ui_bottom_label_plate_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_bottom_label_plate_01_instance_03.png": "assets/toyhouse-ui-v3/ui_bottom_label_plate_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_small_badge_01_instance_02.png": "assets/toyhouse-ui-v3/ui_small_badge_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_small_badge_01_instance_03.png": "assets/toyhouse-ui-v3/ui_small_badge_01_instance_01.png",
  "assets/toyhouse-ui-v3/ui_title_star_01_instance_02.png": "assets/toyhouse-ui-v3/ui_title_star_01_instance_01.png",
  "assets/level-complete-v1/ui_divider_line_right.png": "assets/level-complete-v1/ui_divider_line.png",
  "assets/level-complete-v1/ui_divider_star_right_inner.png": "assets/level-complete-v1/ui_divider_star_left_inner.png",
  "assets/level-complete-v1/ui_divider_star_right_outer.png": "assets/level-complete-v1/ui_divider_star_left_inner.png",
  "assets/level-complete-v1/ui_hint_star_left_outer.png": "assets/level-complete-v1/ui_divider_star_left_inner.png",
  "assets/level-complete-v1/ui_hint_star_right_outer.png": "assets/level-complete-v1/ui_divider_star_left_inner.png"
};
